apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80   # External port that you will use to access the service
      targetPort: 5000  # Port on the container where Flask is listening
